# Generated by Django 3.0.3 on 2020-02-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('group_user', models.CharField(max_length=50, verbose_name='Группа пользователя')),
                ('session_key', models.CharField(max_length=150, verbose_name='Сессия пользователя')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильность ответа')),
                ('otv', models.IntegerField(default=0, null=True, verbose_name='Не правильный ответ')),
                ('vop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions')),
            ],
        ),
    ]
