# Generated by Django 3.0.3 on 2020-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200211_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersanswer',
            name='user',
            field=models.CharField(max_length=20, verbose_name='Пользователь'),
        ),
    ]
