# Generated by Django 3.0.3 on 2020-02-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20200212_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpermitusers',
            old_name='user',
            new_name='user_id',
        ),
    ]
